/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type { } from '@payloadcms/db-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    profilePicture: integer('profile_picture_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    title: text('title'),
    bio: text('bio'),
    dskmPassingYear: numeric('dskm_passing_year', { mode: 'number' }),
    major: text('major'),
    address: integer('address_id').references(() => address.id, {
      onDelete: 'set null',
    }),
    contactEmail: text('contact_email'),
    phone: text('phone'),
    linkedInUrl: text('linked_in_url'),
    facebookUrl: text('facebook_url'),
    websiteUrl: text('website_url'),
    name: text('name').notNull(),
    email: text('email').notNull(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false),
    image: text('image'),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    role: text('role').default('user'),
    banned: integer('banned', { mode: 'boolean' }).default(false),
    banReason: text('ban_reason'),
    banExpires: text('ban_expires').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_profile_picture_idx').on(columns.profilePicture),
    index('users_address_idx').on(columns.address),
    uniqueIndex('users_email_idx').on(columns.email),
    index('users_created_at_idx').on(columns.createdAt),
    index('users_updated_at_idx').on(columns.updatedAt),
  ],
)

export const user_sessions = sqliteTable(
  'user_sessions',
  {
    id: integer('id').primaryKey(),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    token: text('token').notNull(),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    impersonatedBy: text('impersonated_by'),
  },
  (columns) => [
    uniqueIndex('user_sessions_token_idx').on(columns.token),
    index('user_sessions_created_at_idx').on(columns.createdAt),
    index('user_sessions_updated_at_idx').on(columns.updatedAt),
    index('user_sessions_user_idx').on(columns.user),
  ],
)

export const user_accounts = sqliteTable(
  'user_accounts',
  {
    id: integer('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: text('access_token_expires_at').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    refreshTokenExpiresAt: text('refresh_token_expires_at').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    scope: text('scope'),
    password: text('password'),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('user_accounts_account_id_idx').on(columns.accountId),
    index('user_accounts_user_idx').on(columns.user),
    index('user_accounts_access_token_expires_at_idx').on(columns.accessTokenExpiresAt),
    index('user_accounts_refresh_token_expires_at_idx').on(columns.refreshTokenExpiresAt),
    index('user_accounts_created_at_idx').on(columns.createdAt),
    index('user_accounts_updated_at_idx').on(columns.updatedAt),
  ],
)

export const verifications = sqliteTable(
  'verifications',
  {
    id: integer('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('verifications_identifier_idx').on(columns.identifier),
    index('verifications_expires_at_idx').on(columns.expiresAt),
    index('verifications_created_at_idx').on(columns.createdAt),
    index('verifications_updated_at_idx').on(columns.updatedAt),
  ],
)

export const admin_invitations = sqliteTable(
  'admin_invitations',
  {
    id: integer('id').primaryKey(),
    role: text('role', { enum: ['admin', 'user'] })
      .notNull()
      .default('admin'),
    token: text('token').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('admin_invitations_token_idx').on(columns.token),
    index('admin_invitations_updated_at_idx').on(columns.updatedAt),
    index('admin_invitations_created_at_idx').on(columns.createdAt),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt').notNull(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: text('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: text('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: text('sizes_thumbnail_filename'),
    sizes_profile_url: text('sizes_profile_url'),
    sizes_profile_width: numeric('sizes_profile_width', { mode: 'number' }),
    sizes_profile_height: numeric('sizes_profile_height', { mode: 'number' }),
    sizes_profile_mimeType: text('sizes_profile_mime_type'),
    sizes_profile_filesize: numeric('sizes_profile_filesize', { mode: 'number' }),
    sizes_profile_filename: text('sizes_profile_filename'),
  },
  (columns) => [
    index('media_user_idx').on(columns.user),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_profile_sizes_profile_filename_idx').on(columns.sizes_profile_filename),
  ],
)

export const address = sqliteTable(
  'address',
  {
    id: integer('id').primaryKey(),
    presentAddress_street: text('present_address_street'),
    presentAddress_city: text('present_address_city'),
    presentAddress_state: text('present_address_state'),
    presentAddress_postalCode: text('present_address_postal_code'),
    presentAddress_country: text('present_address_country').notNull(),
    permanentAddress_street: text('permanent_address_street'),
    permanentAddress_city: text('permanent_address_city'),
    permanentAddress_state: text('permanent_address_state'),
    permanentAddress_postalCode: text('permanent_address_postal_code'),
    permanentAddress_country: text('permanent_address_country').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('address_updated_at_idx').on(columns.updatedAt),
    index('address_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    userSessionsID: integer('user_sessions_id'),
    userAccountsID: integer('user_accounts_id'),
    verificationsID: integer('verifications_id'),
    'admin-invitationsID': integer('admin_invitations_id'),
    mediaID: integer('media_id'),
    addressID: integer('address_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_user_sessions_id_idx').on(columns.userSessionsID),
    index('payload_locked_documents_rels_user_accounts_id_idx').on(columns.userAccountsID),
    index('payload_locked_documents_rels_verifications_id_idx').on(columns.verificationsID),
    index('payload_locked_documents_rels_admin_invitations_id_idx').on(
      columns['admin-invitationsID'],
    ),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_address_id_idx').on(columns.addressID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_1_idx',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['userSessionsID']],
      foreignColumns: [user_sessions.id],
      name: 'payload_locked_documents_rels_user_sessions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['userAccountsID']],
      foreignColumns: [user_accounts.id],
      name: 'payload_locked_documents_rels_user_accounts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['verificationsID']],
      foreignColumns: [verifications.id],
      name: 'payload_locked_documents_rels_verifications_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['admin-invitationsID']],
      foreignColumns: [admin_invitations.id],
      name: 'payload_locked_documents_rels_admin_invitations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['addressID']],
      foreignColumns: [address.id],
      name: 'payload_locked_documents_rels_address_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_1_idx',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users = relations(users, ({ one }) => ({
  profilePicture: one(media, {
    fields: [users.profilePicture],
    references: [media.id],
    relationName: 'profilePicture',
  }),
  address: one(address, {
    fields: [users.address],
    references: [address.id],
    relationName: 'address',
  }),
}))
export const relations_user_sessions = relations(user_sessions, ({ one }) => ({
  user: one(users, {
    fields: [user_sessions.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_user_accounts = relations(user_accounts, ({ one }) => ({
  user: one(users, {
    fields: [user_accounts.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_verifications = relations(verifications, () => ({}))
export const relations_admin_invitations = relations(admin_invitations, () => ({}))
export const relations_media = relations(media, ({ one }) => ({
  user: one(users, {
    fields: [media.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_address = relations(address, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    userSessionsID: one(user_sessions, {
      fields: [payload_locked_documents_rels.userSessionsID],
      references: [user_sessions.id],
      relationName: 'userSessions',
    }),
    userAccountsID: one(user_accounts, {
      fields: [payload_locked_documents_rels.userAccountsID],
      references: [user_accounts.id],
      relationName: 'userAccounts',
    }),
    verificationsID: one(verifications, {
      fields: [payload_locked_documents_rels.verificationsID],
      references: [verifications.id],
      relationName: 'verifications',
    }),
    'admin-invitationsID': one(admin_invitations, {
      fields: [payload_locked_documents_rels['admin-invitationsID']],
      references: [admin_invitations.id],
      relationName: 'admin-invitations',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    addressID: one(address, {
      fields: [payload_locked_documents_rels.addressID],
      references: [address.id],
      relationName: 'address',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  users: typeof users
  user_sessions: typeof user_sessions
  user_accounts: typeof user_accounts
  verifications: typeof verifications
  admin_invitations: typeof admin_invitations
  media: typeof media
  address: typeof address
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users: typeof relations_users
  relations_user_sessions: typeof relations_user_sessions
  relations_user_accounts: typeof relations_user_accounts
  relations_verifications: typeof relations_verifications
  relations_admin_invitations: typeof relations_admin_invitations
  relations_media: typeof relations_media
  relations_address: typeof relations_address
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
